# Generated by Django 4.0.2 on 2022-02-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imageprocess',
            table='myapp_image',
        ),
    ]
